### ISSUE TITLE
HDMI to CSI2

### ISSUE THREAD

**Issue by DerHerr187** [lehmenkuehler/camera-triggerbot#9]
Hi the stream is working but because i use a hdmi to csi 2 adapter the crosshair is wayy too big how can is "zoom" in more ? ive tried all kinds of settings and also change the resolution but the stream didnt zoom but only get more blurry

thanks in advance

**Comment by DerHerr187** [comment]
i think Theres No was to Change It with any keybinds but ive found the camera.zoom command which hopefully works bugless.
Another question is: im confused as to how the Marker color works so It knows when im scoped in. It says in the Code It uses the color from config but Marker color in config says "scoped in Marker color" but Theres is No scoped in Marker color in Cs ??

**Comment by lehmenkuehler** [comment]
Hey, sorry, I haven't tested HDMI to CSI-2 adapters but I'm assuming there would be a delay with them. The marker color feature requires a color indicator on the crosshair when scoped in, CS doesn't have that.
